mysql:
  image: mysql:5.5.51
  environment:
    MYSQL_ROOT_PASSWORD: fizzbuzz
  ports:
    - "3310:3306"
web:
  build: .
  #command: bundle exec unicorn
  command: bundle exec rails s
  volumes:
    # This seems to work as-is once you expose /Users to the boot2docker vm.
    - .:/il_yanzhao
  links:
    - mysql
  ports:
    - "6001:3000"
  volumes_from:
    - bundle


  log_driver: "json-file"
  log_opt:
    max-size: "10k"
    max-file: "20"

bundle:
  # 'image' will vary depending on your docker-compose 
  # project name. You may need to run `docker-compose build web`
  # before this works.
  image: ilyanzhaolite_web
  command: echo "I'm a little data container, short and stout..."
  volumes:
    - /bundle

