require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FeeInfosController do

  def mock_fee_info(stubs={})
    @mock_fee_info ||= mock_model(FeeInfo, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all fee_infos as @fee_infos" do
      FeeInfo.stub(:all) { [mock_fee_info] }
      get :index
      assigns(:fee_infos).should eq([mock_fee_info])
    end
  end

  describe "GET show" do
    it "assigns the requested fee_info as @fee_info" do
      FeeInfo.stub(:find).with("37") { mock_fee_info }
      get :show, :id => "37"
      assigns(:fee_info).should be(mock_fee_info)
    end
  end

  describe "GET new" do
    it "assigns a new fee_info as @fee_info" do
      FeeInfo.stub(:new) { mock_fee_info }
      get :new
      assigns(:fee_info).should be(mock_fee_info)
    end
  end

  describe "GET edit" do
    it "assigns the requested fee_info as @fee_info" do
      FeeInfo.stub(:find).with("37") { mock_fee_info }
      get :edit, :id => "37"
      assigns(:fee_info).should be(mock_fee_info)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created fee_info as @fee_info" do
        FeeInfo.stub(:new).with({'these' => 'params'}) { mock_fee_info(:save => true) }
        post :create, :fee_info => {'these' => 'params'}
        assigns(:fee_info).should be(mock_fee_info)
      end

      it "redirects to the created fee_info" do
        FeeInfo.stub(:new) { mock_fee_info(:save => true) }
        post :create, :fee_info => {}
        response.should redirect_to(fee_info_url(mock_fee_info))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fee_info as @fee_info" do
        FeeInfo.stub(:new).with({'these' => 'params'}) { mock_fee_info(:save => false) }
        post :create, :fee_info => {'these' => 'params'}
        assigns(:fee_info).should be(mock_fee_info)
      end

      it "re-renders the 'new' template" do
        FeeInfo.stub(:new) { mock_fee_info(:save => false) }
        post :create, :fee_info => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fee_info" do
        FeeInfo.stub(:find).with("37") { mock_fee_info }
        mock_fee_info.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :fee_info => {'these' => 'params'}
      end

      it "assigns the requested fee_info as @fee_info" do
        FeeInfo.stub(:find) { mock_fee_info(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:fee_info).should be(mock_fee_info)
      end

      it "redirects to the fee_info" do
        FeeInfo.stub(:find) { mock_fee_info(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(fee_info_url(mock_fee_info))
      end
    end

    describe "with invalid params" do
      it "assigns the fee_info as @fee_info" do
        FeeInfo.stub(:find) { mock_fee_info(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:fee_info).should be(mock_fee_info)
      end

      it "re-renders the 'edit' template" do
        FeeInfo.stub(:find) { mock_fee_info(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fee_info" do
      FeeInfo.stub(:find).with("37") { mock_fee_info }
      mock_fee_info.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the fee_infos list" do
      FeeInfo.stub(:find) { mock_fee_info }
      delete :destroy, :id => "1"
      response.should redirect_to(fee_infos_url)
    end
  end

end
