require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe HandKidsTransitBillsController do

  def mock_hand_kids_transit_bill(stubs={})
    @mock_hand_kids_transit_bill ||= mock_model(HandKidsTransitBill, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all hand_kids_transit_bills as @hand_kids_transit_bills" do
      HandKidsTransitBill.stub(:all) { [mock_hand_kids_transit_bill] }
      get :index
      assigns(:hand_kids_transit_bills).should eq([mock_hand_kids_transit_bill])
    end
  end

  describe "GET show" do
    it "assigns the requested hand_kids_transit_bill as @hand_kids_transit_bill" do
      HandKidsTransitBill.stub(:find).with("37") { mock_hand_kids_transit_bill }
      get :show, :id => "37"
      assigns(:hand_kids_transit_bill).should be(mock_hand_kids_transit_bill)
    end
  end

  describe "GET new" do
    it "assigns a new hand_kids_transit_bill as @hand_kids_transit_bill" do
      HandKidsTransitBill.stub(:new) { mock_hand_kids_transit_bill }
      get :new
      assigns(:hand_kids_transit_bill).should be(mock_hand_kids_transit_bill)
    end
  end

  describe "GET edit" do
    it "assigns the requested hand_kids_transit_bill as @hand_kids_transit_bill" do
      HandKidsTransitBill.stub(:find).with("37") { mock_hand_kids_transit_bill }
      get :edit, :id => "37"
      assigns(:hand_kids_transit_bill).should be(mock_hand_kids_transit_bill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created hand_kids_transit_bill as @hand_kids_transit_bill" do
        HandKidsTransitBill.stub(:new).with({'these' => 'params'}) { mock_hand_kids_transit_bill(:save => true) }
        post :create, :hand_kids_transit_bill => {'these' => 'params'}
        assigns(:hand_kids_transit_bill).should be(mock_hand_kids_transit_bill)
      end

      it "redirects to the created hand_kids_transit_bill" do
        HandKidsTransitBill.stub(:new) { mock_hand_kids_transit_bill(:save => true) }
        post :create, :hand_kids_transit_bill => {}
        response.should redirect_to(hand_kids_transit_bill_url(mock_hand_kids_transit_bill))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hand_kids_transit_bill as @hand_kids_transit_bill" do
        HandKidsTransitBill.stub(:new).with({'these' => 'params'}) { mock_hand_kids_transit_bill(:save => false) }
        post :create, :hand_kids_transit_bill => {'these' => 'params'}
        assigns(:hand_kids_transit_bill).should be(mock_hand_kids_transit_bill)
      end

      it "re-renders the 'new' template" do
        HandKidsTransitBill.stub(:new) { mock_hand_kids_transit_bill(:save => false) }
        post :create, :hand_kids_transit_bill => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hand_kids_transit_bill" do
        HandKidsTransitBill.stub(:find).with("37") { mock_hand_kids_transit_bill }
        mock_hand_kids_transit_bill.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :hand_kids_transit_bill => {'these' => 'params'}
      end

      it "assigns the requested hand_kids_transit_bill as @hand_kids_transit_bill" do
        HandKidsTransitBill.stub(:find) { mock_hand_kids_transit_bill(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:hand_kids_transit_bill).should be(mock_hand_kids_transit_bill)
      end

      it "redirects to the hand_kids_transit_bill" do
        HandKidsTransitBill.stub(:find) { mock_hand_kids_transit_bill(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(hand_kids_transit_bill_url(mock_hand_kids_transit_bill))
      end
    end

    describe "with invalid params" do
      it "assigns the hand_kids_transit_bill as @hand_kids_transit_bill" do
        HandKidsTransitBill.stub(:find) { mock_hand_kids_transit_bill(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:hand_kids_transit_bill).should be(mock_hand_kids_transit_bill)
      end

      it "re-renders the 'edit' template" do
        HandKidsTransitBill.stub(:find) { mock_hand_kids_transit_bill(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hand_kids_transit_bill" do
      HandKidsTransitBill.stub(:find).with("37") { mock_hand_kids_transit_bill }
      mock_hand_kids_transit_bill.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the hand_kids_transit_bills list" do
      HandKidsTransitBill.stub(:find) { mock_hand_kids_transit_bill }
      delete :destroy, :id => "1"
      response.should redirect_to(hand_kids_transit_bills_url)
    end
  end

end
