require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe KidsTransitBillsController do

  def mock_kids_transit_bill(stubs={})
    @mock_kids_transit_bill ||= mock_model(KidsTransitBill, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all kids_transit_bills as @kids_transit_bills" do
      KidsTransitBill.stub(:all) { [mock_kids_transit_bill] }
      get :index
      assigns(:kids_transit_bills).should eq([mock_kids_transit_bill])
    end
  end

  describe "GET show" do
    it "assigns the requested kids_transit_bill as @kids_transit_bill" do
      KidsTransitBill.stub(:find).with("37") { mock_kids_transit_bill }
      get :show, :id => "37"
      assigns(:kids_transit_bill).should be(mock_kids_transit_bill)
    end
  end

  describe "GET new" do
    it "assigns a new kids_transit_bill as @kids_transit_bill" do
      KidsTransitBill.stub(:new) { mock_kids_transit_bill }
      get :new
      assigns(:kids_transit_bill).should be(mock_kids_transit_bill)
    end
  end

  describe "GET edit" do
    it "assigns the requested kids_transit_bill as @kids_transit_bill" do
      KidsTransitBill.stub(:find).with("37") { mock_kids_transit_bill }
      get :edit, :id => "37"
      assigns(:kids_transit_bill).should be(mock_kids_transit_bill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created kids_transit_bill as @kids_transit_bill" do
        KidsTransitBill.stub(:new).with({'these' => 'params'}) { mock_kids_transit_bill(:save => true) }
        post :create, :kids_transit_bill => {'these' => 'params'}
        assigns(:kids_transit_bill).should be(mock_kids_transit_bill)
      end

      it "redirects to the created kids_transit_bill" do
        KidsTransitBill.stub(:new) { mock_kids_transit_bill(:save => true) }
        post :create, :kids_transit_bill => {}
        response.should redirect_to(kids_transit_bill_url(mock_kids_transit_bill))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved kids_transit_bill as @kids_transit_bill" do
        KidsTransitBill.stub(:new).with({'these' => 'params'}) { mock_kids_transit_bill(:save => false) }
        post :create, :kids_transit_bill => {'these' => 'params'}
        assigns(:kids_transit_bill).should be(mock_kids_transit_bill)
      end

      it "re-renders the 'new' template" do
        KidsTransitBill.stub(:new) { mock_kids_transit_bill(:save => false) }
        post :create, :kids_transit_bill => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested kids_transit_bill" do
        KidsTransitBill.stub(:find).with("37") { mock_kids_transit_bill }
        mock_kids_transit_bill.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :kids_transit_bill => {'these' => 'params'}
      end

      it "assigns the requested kids_transit_bill as @kids_transit_bill" do
        KidsTransitBill.stub(:find) { mock_kids_transit_bill(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:kids_transit_bill).should be(mock_kids_transit_bill)
      end

      it "redirects to the kids_transit_bill" do
        KidsTransitBill.stub(:find) { mock_kids_transit_bill(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(kids_transit_bill_url(mock_kids_transit_bill))
      end
    end

    describe "with invalid params" do
      it "assigns the kids_transit_bill as @kids_transit_bill" do
        KidsTransitBill.stub(:find) { mock_kids_transit_bill(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:kids_transit_bill).should be(mock_kids_transit_bill)
      end

      it "re-renders the 'edit' template" do
        KidsTransitBill.stub(:find) { mock_kids_transit_bill(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested kids_transit_bill" do
      KidsTransitBill.stub(:find).with("37") { mock_kids_transit_bill }
      mock_kids_transit_bill.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the kids_transit_bills list" do
      KidsTransitBill.stub(:find) { mock_kids_transit_bill }
      delete :destroy, :id => "1"
      response.should redirect_to(kids_transit_bills_url)
    end
  end

end
