require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe VehicleFeesController do

  def mock_vehicle_fee(stubs={})
    @mock_vehicle_fee ||= mock_model(VehicleFee, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all vehicle_fees as @vehicle_fees" do
      VehicleFee.stub(:all) { [mock_vehicle_fee] }
      get :index
      assigns(:vehicle_fees).should eq([mock_vehicle_fee])
    end
  end

  describe "GET show" do
    it "assigns the requested vehicle_fee as @vehicle_fee" do
      VehicleFee.stub(:find).with("37") { mock_vehicle_fee }
      get :show, :id => "37"
      assigns(:vehicle_fee).should be(mock_vehicle_fee)
    end
  end

  describe "GET new" do
    it "assigns a new vehicle_fee as @vehicle_fee" do
      VehicleFee.stub(:new) { mock_vehicle_fee }
      get :new
      assigns(:vehicle_fee).should be(mock_vehicle_fee)
    end
  end

  describe "GET edit" do
    it "assigns the requested vehicle_fee as @vehicle_fee" do
      VehicleFee.stub(:find).with("37") { mock_vehicle_fee }
      get :edit, :id => "37"
      assigns(:vehicle_fee).should be(mock_vehicle_fee)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created vehicle_fee as @vehicle_fee" do
        VehicleFee.stub(:new).with({'these' => 'params'}) { mock_vehicle_fee(:save => true) }
        post :create, :vehicle_fee => {'these' => 'params'}
        assigns(:vehicle_fee).should be(mock_vehicle_fee)
      end

      it "redirects to the created vehicle_fee" do
        VehicleFee.stub(:new) { mock_vehicle_fee(:save => true) }
        post :create, :vehicle_fee => {}
        response.should redirect_to(vehicle_fee_url(mock_vehicle_fee))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vehicle_fee as @vehicle_fee" do
        VehicleFee.stub(:new).with({'these' => 'params'}) { mock_vehicle_fee(:save => false) }
        post :create, :vehicle_fee => {'these' => 'params'}
        assigns(:vehicle_fee).should be(mock_vehicle_fee)
      end

      it "re-renders the 'new' template" do
        VehicleFee.stub(:new) { mock_vehicle_fee(:save => false) }
        post :create, :vehicle_fee => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vehicle_fee" do
        VehicleFee.stub(:find).with("37") { mock_vehicle_fee }
        mock_vehicle_fee.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :vehicle_fee => {'these' => 'params'}
      end

      it "assigns the requested vehicle_fee as @vehicle_fee" do
        VehicleFee.stub(:find) { mock_vehicle_fee(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:vehicle_fee).should be(mock_vehicle_fee)
      end

      it "redirects to the vehicle_fee" do
        VehicleFee.stub(:find) { mock_vehicle_fee(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(vehicle_fee_url(mock_vehicle_fee))
      end
    end

    describe "with invalid params" do
      it "assigns the vehicle_fee as @vehicle_fee" do
        VehicleFee.stub(:find) { mock_vehicle_fee(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:vehicle_fee).should be(mock_vehicle_fee)
      end

      it "re-renders the 'edit' template" do
        VehicleFee.stub(:find) { mock_vehicle_fee(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vehicle_fee" do
      VehicleFee.stub(:find).with("37") { mock_vehicle_fee }
      mock_vehicle_fee.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the vehicle_fees list" do
      VehicleFee.stub(:find) { mock_vehicle_fee }
      delete :destroy, :id => "1"
      response.should redirect_to(vehicle_fees_url)
    end
  end

end
