require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe VehicleFeeLinesController do

  def mock_vehicle_fee_line(stubs={})
    @mock_vehicle_fee_line ||= mock_model(VehicleFeeLine, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all vehicle_fee_lines as @vehicle_fee_lines" do
      VehicleFeeLine.stub(:all) { [mock_vehicle_fee_line] }
      get :index
      assigns(:vehicle_fee_lines).should eq([mock_vehicle_fee_line])
    end
  end

  describe "GET show" do
    it "assigns the requested vehicle_fee_line as @vehicle_fee_line" do
      VehicleFeeLine.stub(:find).with("37") { mock_vehicle_fee_line }
      get :show, :id => "37"
      assigns(:vehicle_fee_line).should be(mock_vehicle_fee_line)
    end
  end

  describe "GET new" do
    it "assigns a new vehicle_fee_line as @vehicle_fee_line" do
      VehicleFeeLine.stub(:new) { mock_vehicle_fee_line }
      get :new
      assigns(:vehicle_fee_line).should be(mock_vehicle_fee_line)
    end
  end

  describe "GET edit" do
    it "assigns the requested vehicle_fee_line as @vehicle_fee_line" do
      VehicleFeeLine.stub(:find).with("37") { mock_vehicle_fee_line }
      get :edit, :id => "37"
      assigns(:vehicle_fee_line).should be(mock_vehicle_fee_line)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created vehicle_fee_line as @vehicle_fee_line" do
        VehicleFeeLine.stub(:new).with({'these' => 'params'}) { mock_vehicle_fee_line(:save => true) }
        post :create, :vehicle_fee_line => {'these' => 'params'}
        assigns(:vehicle_fee_line).should be(mock_vehicle_fee_line)
      end

      it "redirects to the created vehicle_fee_line" do
        VehicleFeeLine.stub(:new) { mock_vehicle_fee_line(:save => true) }
        post :create, :vehicle_fee_line => {}
        response.should redirect_to(vehicle_fee_line_url(mock_vehicle_fee_line))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vehicle_fee_line as @vehicle_fee_line" do
        VehicleFeeLine.stub(:new).with({'these' => 'params'}) { mock_vehicle_fee_line(:save => false) }
        post :create, :vehicle_fee_line => {'these' => 'params'}
        assigns(:vehicle_fee_line).should be(mock_vehicle_fee_line)
      end

      it "re-renders the 'new' template" do
        VehicleFeeLine.stub(:new) { mock_vehicle_fee_line(:save => false) }
        post :create, :vehicle_fee_line => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vehicle_fee_line" do
        VehicleFeeLine.stub(:find).with("37") { mock_vehicle_fee_line }
        mock_vehicle_fee_line.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :vehicle_fee_line => {'these' => 'params'}
      end

      it "assigns the requested vehicle_fee_line as @vehicle_fee_line" do
        VehicleFeeLine.stub(:find) { mock_vehicle_fee_line(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:vehicle_fee_line).should be(mock_vehicle_fee_line)
      end

      it "redirects to the vehicle_fee_line" do
        VehicleFeeLine.stub(:find) { mock_vehicle_fee_line(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(vehicle_fee_line_url(mock_vehicle_fee_line))
      end
    end

    describe "with invalid params" do
      it "assigns the vehicle_fee_line as @vehicle_fee_line" do
        VehicleFeeLine.stub(:find) { mock_vehicle_fee_line(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:vehicle_fee_line).should be(mock_vehicle_fee_line)
      end

      it "re-renders the 'edit' template" do
        VehicleFeeLine.stub(:find) { mock_vehicle_fee_line(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vehicle_fee_line" do
      VehicleFeeLine.stub(:find).with("37") { mock_vehicle_fee_line }
      mock_vehicle_fee_line.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the vehicle_fee_lines list" do
      VehicleFeeLine.stub(:find) { mock_vehicle_fee_line }
      delete :destroy, :id => "1"
      response.should redirect_to(vehicle_fee_lines_url)
    end
  end

end
